{% set name = "xpdview" %}
{% set version = "0.5.0" %}
{% set sha256 = "c3ae0eca0e193637627fd80a9614cc5f462b4f0dcb85d6da60a3979f99a042cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - bluesky
    - numpy
    - cycler

test:
  imports:
    - xpdview
    - xpdview.callbacks

about:
  home: http://github.com/xpdAcq/xpdView
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Visualization for x-ray scattering data'

extra:
  recipe-maintainers:
    - CJ-Wright 
