{% set name = "xpdview" %}
{% set version = "0.4.0" %}
{% set sha256 = "7bc19e22c1ed244874c616cf39b6afcad49ed76f679ce12fe9427aa8e07cb008" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - bluesky
    - numpy
    - cycler

test:
  imports:
    - xpdview
    - xpdview.callbacks

about:
  home: http://github.com/xpdAcq/xpdView
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Visualization for x-ray scattering data'

extra:
  recipe-maintainers:
    - CJ-Wright 
