{% set name = "xpdview" %}
{% set version = "0.5.1" %}
{% set sha256 = "c65fcb7e2fab7afd309b71da8011f1690771ba0a32e6fb2f65abeb33d64aa0e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - bluesky
    - numpy
    - cycler

test:
  imports:
    - xpdview
    - xpdview.callbacks

about:
  home: http://github.com/xpdAcq/xpdView
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Visualization for x-ray scattering data'

extra:
  recipe-maintainers:
    - CJ-Wright 
