travis:
  secure:
    BINSTAR_TOKEN: Z0PkhNFasTnk1dEc4nfQPBWSrnRtlK/F7LWvZj42W08tNa2/8MJtlN14xgyIpoNDYzy03CzKzafEAunyEzFRv8nwwjvCxMcMQPE79VH6QtH+Xn9yhuPYqDdvUzQF6s28RLLGJvUtOCwCXyWUMI6Bn+sW6BSf3ApaNwLoKyWBgRUUC25Od6Ojdi+cfeW1gZSVplctMOLxYVVhhxnrFrXZNJy/7e7DjL+yPk2zc1MUo0wwmNuMzHuAB3sLpEyZW8b4tIGe9x6bcAi2onHqYO2TOlAOwqf8KKJgc8OJyvg2ea/MHTeJCihxmdPVE0PqofW1DcEV967vgrY92Usb5g5Q9+J0Fqh0LjsV624KTRv5hUmH3En2jr0zyuCrlLdb8me/zNO732zXXYePpMZoWAvKKnhOWobrs9ZVoaLt1MStqHPUl70eAjDrLRd6KMNLvs5ErTK6/pIDmM73Ihk5F5DASdnD4bRcewYmB7RryEPhiJ48TTjWFVbRMdDCrqPX/G7NAHiXoey0nAxNtqyQaG/fzHoBFbc1lrEqODvno0xpcWKkuMsqllyNqxa1S/zih928lw+xp/Nok3cnCW6JuS0ka7bS1MLMtx4Y4bw/wVYPlgQrkHpFSGCfOdf8a42q3hx0WiWnWwguIgTpI7USdEKUfiyDsW+Ri9IdXHKu8Z7goPo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
